name: tp7
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"  # Ensure compatibility with future versions

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons for iOS-style icons
  cupertino_icons: ^1.0.2
  flutter_slidable: ^3.0.0
  intl: ^0.18.1
  http: ^1.1.0
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_lints package provides recommended lints
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Optionally, if you're planning to add assets, uncomment and specify them
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Optionally, if you're using custom fonts, add them here
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
